# defaults:
#   - _self_
#   - robot: g1_29dof
#   - obs: mosaic
#   - sim: mujoco
#   - env: mosaic
#   - agent: mosaic
#   - mimic: eval

defaults:
  - _self_
  - robot: g1_23dof_gmt # g1_29dof
  - obs: gmt
  - sim: mujoco
  - env: gmt
  - agent: gmt
  - mimic: eval

device: cpu

